### ISSUE TITLE
Error Code

### ISSUE THREAD

**Issue by mrsgpmrsgp** [xtekky/zefoy#14]
hi guys, i will inform you about this error

`Exception in thread Thread-1 (timez):
Traceback (most recent call last):
  File "C:\Users\PENAMEDIA OFFICIAL\AppData\Local\Programs\Python\Python310\Lib\threading.py", line 1016, in _bootstrap_inner
Traceback (most recent call last):
  File "C:\Users\PENAMEDIA OFFICIAL\Desktop\bot\zefoy\source.py", line 1185, in <module>
    self.run()
  File "C:\Users\PENAMEDIA OFFICIAL\AppData\Local\Programs\Python\Python310\Lib\threading.py", line 953, in run
    chrome_options = Options()
NameError: name 'Options' is not defined
    self._target(*self._args, **self._kwargs)
  File "C:\Users\PENAMEDIA OFFICIAL\Desktop\bot\zefoy\source.py", line 41, in timez
    now = datetime.now()
NameError: name 'datetime' is not defined`

**Comment by JustShimaru** [comment]
got this too

**Comment by xtekky** [comment]
I did not work on the code for a long time, I have to update it
